# Generated by Django 4.2.7 on 2023-11-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(max_length=100)),
                ('bowling_team', models.CharField(max_length=100)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=100)),
                ('non_striker', models.CharField(max_length=100)),
                ('bowler', models.CharField(max_length=100)),
                ('is_super_over', models.IntegerField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(max_length=100, null=True)),
                ('dismissal_kind', models.CharField(max_length=100, null=True)),
                ('fielder', models.CharField(max_length=100, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.matches')),
            ],
        ),
    ]
